/**
 * adminEditor.js
 *
 * Dic 15 2017, layouts o grid:
 * Casos de estudio
 * https://stackoverflow.com/questions/24695323/tinymce-listbox-onsubmit-giving-object-object-rather-than-value
 * https://stackoverflow.com/questions/23476463/wordpress-tinymce-add-a-description-to-a-popup-form
 * 
 * Oficial tinyMce.
 * https://www.tinymce.com/docs/advanced/creating-custom-dialogs/
 * https://www.tinymce.com/docs/demo/custom-toolbar-listbox/
 * 
 * Ejemplo de dialogo
 * https://jsfiddle.net/aeutaoLf/2/
 *
 */

( function ( $ ) {
    tinymce.PluginManager.add('custom_mce_button5', function(editor, url) {
    	
        editor.addButton('custom_mce_button5', {
            //icon: false,
            //title : 'Insert Google map',
            //text: 'Insert Google map',
            title : editor.getLang('ekiline_tinymce.insertgmap'),
            image: '../wp-content/themes/ekiline/img/ico-gmap.png',
            onclick: function (e) {            	
                editor.windowManager.open({
                	
                    //title: 'Paste link generated by google maps',
		            title : editor.getLang('ekiline_tinymce.insertgmap'),
                    minWidth: 500,
                    minHeight: 100,

                    body: [
						{
                        	type	: 'label',
                        	text	: editor.getLang('ekiline_tinymce.pastegmap'),
                    	},
                    // item 1, map field
						{
                        	type	: 'textbox',
                        	name	: 'tagMap',
                    	},
                    // item 2, case modify height
						{
				            label   : editor.getLang('ekiline_tinymce.changeheight'),
                        	type	: 'textbox',
                        	name	: 'heightMap',
                        	value 	: '',
                    	},
	                          	
                	],                    	
                    onsubmit: function (e) {
                    	
						var newMap = e.data.tagMap;
						var newHeight = e.data.heightMap;

						// create element and set string as it's content
						var $bootmap = $('<div class="map-responsive">').html( newMap );
						
						// modify attributes
						if ( newHeight != '' ){
							$bootmap.find('iframe').attr('height', newHeight );
						}
						// return modified content to string
						var processedHTML = $bootmap.html();
						
						console.log(processedHTML);

                        editor.insertContent( processedHTML + '<br><br>' );

                        //editor.insertContent( '<div class="map-responsive"> ' + newMap + ' </div><br><br>' );
                        
                    }
                    
                }); //editor.windowManager.open
                
            }
        });
    });
} )( jQuery );
