<?php
/**
 * Function to automatically create a standard sitemap.xml
 * https://www.itsupportguides.com/knowledge-base/wordpress/wordpress-how-to-automatically-create-sitemap-xml-without-plugin/
 * https://blog.jallet.org/generer-un-fichier-sitemap-xml-sans-plugin-490.html
 * https://codex.wordpress.org/Filesystem_API
 * https://www.sitemaps.org/protocol.html
 *
 * @package ekiline
 */
 
add_action( 'publish_post', 'ekiline_sitemap_xml' ) ;
add_action( 'publish_page', 'ekiline_sitemap_xml' ) ;

function ekiline_sitemap_xml() {
		
	$sitemap = '' ;
	
	// Adjust timezone to follow XMl standard
	if( str_replace( '-', '', get_option( 'gmt_offset' ) ) < 10 ) {
		$timeZone = '-0' . str_replace( '-', '', get_option( 'gmt_offset' ) ) ;
	} else {
		$timeZone = get_option( 'gmt_offset' ) ;
	}
	
	if( strlen( $timeZone ) == 3 ) {
		$timeZone = $timeZone . ':00' ;
	}
	
	// Select posts and pages
	$postsForSitemap = get_posts(array(
		//	'numberposts' => -1,
			'numberposts' => 20,
			'orderby' => 'modified',
			'post_type' => array( 'post','page' ),
			'order' => 'DESC'
	));
	
	// Sitemap header
	$sitemap .= '<?xml version="1.0" encoding="UTF-8"?>';
	/* $sitemap .= '<?xml-stylesheet type="text/xsl" href="' . esc_url( home_url( '/' ) ) . 'sitemap.xsl"?>' . "\n"; */
	$sitemap .= '<!--Generated by ekiline.com wordpress theme -->' . "\n";
	$sitemap .= '<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";
	// Generate homepage xml set
	$sitemap .= "\t" . '<url>' . "\n" . 
				"\t\t" . '<loc>' . esc_url( home_url( '/' ) ) .'</loc>' . 
				"\n\t\t" . '<lastmod>' . date( "Y-m-d\TH:i:s", current_time( 'timestamp', 0 ) ) . $timeZone . '</lastmod>' . 
				"\n\t\t" . '<changefreq>daily</changefreq>' . 
				"\n\t\t" . '<priority>1.0</priority>' . 
				"\n\t" . '</url>' . "\n" ;

	// Generate entry for each post/page
	foreach( $postsForSitemap as $post ){
		setup_postdata( $post ) ;
		$postdate = explode( ' ', $post->post_modified ) ;
		
		//set priority by type of post
		$priority = '0.8';
		$pfreq = 'weekly';
		$ptype = explode( ' ', $post->post_type ) ;
		if ($ptype[0] == 'page'){ $priority = '0.5'; $pfreq = 'monthly'; }
		
		$sitemap .= "\t" . '<url>' . "\n" . 
					"\t\t" . '<loc>' . get_permalink($post->ID) . '</loc>' . 
					"\n\t\t" . '<lastmod>' . $postdate[0] . 'T' . $postdate[1] . $timeZone . '</lastmod>' . 
					"\n\t\t" . '<changefreq>' . $pfreq . '</changefreq>' . 
					"\n\t\t" . '<priority>' . $priority . '</priority>' . 
					"\n\t" . '</url>' . "\n" ;
	}

	// Sitemap closing tag
	$sitemap .= '</urlset>' ;
	
	// Write sitemap.xml using WordPress file system class
	// See https ://wordpress.stackexchange.com/questions/120273/converting-fopen-fwrite-operations-to-wp-filesystem
	
	WP_Filesystem();
	global $wp_filesystem;
	
	$homedir = $wp_filesystem->abspath();
	$file = trailingslashit( $homedir ) . 'sitemap.xml';
	$wp_filesystem->put_contents( $file, $sitemap, FS_CHMOD_FILE );
	
}
